name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sudo rm -rf ~/glance
          sudo cd ~
          git clone https://github.com/tedim52/glance.git
          sudo cd ~/glance
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d